language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- CI=false npm run build
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  repo: commonauth/commonauth.github.io
  on:
    branch: master
  fqdn: commonauth.com
